name: Terraform Apply

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]

permissions:
  id-token: write # Required for OIDC token fetching
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/test

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
        working-directory: ./terraform/environments/test